---
- name: Provision multiple micro ec2 instances
  hosts: local
  connection: local
  gather_facts: False

  tasks:
    - name: Provisioning Instnaces
      ec2:
        aws_access_key: AKIA
        aws_secret_key: d0Sw
        region: us-east-1
        key_name: Shared
        instance_type: t2.micro
        image: ami-0de53d8956e8dcf80
        wait: yes
        group_id: sg-0185aa9c06038450f
        count: 1
        vpc_subnet_id: subnet-088b4c11b9c7dd471
        assign_public_ip: yes
      register: web
 
    - name: DevServer | Set the Instances facts
      set_fact:
        instance_private_ip: "{{ web.instances[0].private_ip }}"
        instance_id: "{{ web.instances[0].id }}"

    - name: DevServer | Add the newly created EC2 instance(s) to the local host group (located inside the directory)
      local_action:
        module: lineinfile
        dest: "./hosts"
        regexp: "{{ instance_private_ip }}" 
        insertafter: "[devserver]"
        line: "{{ instance_private_ip }}"    

    
#    - name: Add new instances to host group
#      add_host: hostname={{item.public_ip}} groupname=webserver
#      with_items: ec2.instances 


        

