---
- name: Ansible create host file if it doesn't exist example
  copy: src=hosts dest=/home/ec2-user/ansible/playbooks

- name: Creating a instance file
  copy: src=instances dest=/home/ec2-user/ansible/playbooks

# Instnace 1
#
- name: Provisioning Instances
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: "{{ wait }}"
    group_id: "{{ group_id }}"
    count: "{{ instance_count }}"
    vpc_subnet_id: "{{ vpc_subnet_id1 }}"
    assign_public_ip: "{{ assign_public_ip }}"
    instance_tags:
      Name: "{{ Instance_Name }}"
  register: web
  
- name: Setting the instances facts for DevServers
  set_fact:
    instance_private_ip: "{{ web.instances[0].private_ip }}"
    instance_id: "{{ web.instances[0].id }}"
- name: DevServer | Adding the newly created EC2 instance(s) to the DevServer Inventory file
  local_action:
    module: lineinfile
    dest: "/home/ec2-user/ansible/playbooks/hosts"
    regexp: "{{ instance_private_ip }}"
    insertafter: "[Dev]"
    line: "{{ instance_private_ip }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ web.instances[0].private_ip }}"
    port: 22
    delay: 60
    timeout: 300
  with_items: "{{ web.instances }}"

- name: Adding instance id in the file
  local_action:
    module: lineinfile
    dest: "/home/ec2-user/ansible/playbooks/instances"
    regexp: "{{ instance_id }}"
    line: "{{ instance_id }}"


# Instance 2


- name: Provisioning Instances
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: "{{ wait }}"
    group_id: "{{ group_id }}"
    count: "{{ instance_count }}"
    vpc_subnet_id: "{{ vpc_subnet_id2 }}"
    assign_public_ip: "{{ assign_public_ip }}"
    instance_tags:
      Name: "{{ Instance_Name }}"
  register: web1

- name: Setting the instances facts for DevServers
  set_fact:
    instance_private_ip: "{{ web1.instances[0].private_ip }}"
    instance_id: "{{ web1.instances[0].id }}"
- name: DevServer | Adding the newly created EC2 instance(s) to the DevServer Inventory file
  local_action:
    module: lineinfile
    dest: "/home/ec2-user/ansible/playbooks/hosts"
    regexp: "{{ instance_private_ip }}"
    insertafter: "[Dev]"
    line: "{{ instance_private_ip }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ web1.instances[0].private_ip }}"
    port: 22
    delay: 60
    timeout: 300
  with_items: "{{ web1.instances }}"

- name: Adding instance id in the file
  local_action:
    module: lineinfile
    dest: "/home/ec2-user/ansible/playbooks/instances"
    regexp: "{{ instance_id }}"
    line: "{{ instance_id }}"


